export const wh3e = {
  classes: {
    theDeft: "wh3e.class.theDeft",
    theStrong: "wh3e.class.theStrong",
    theWise: "wh3e.class.theWise",
    theBrave: "wh3e.class.theBrave",
    theFortunate: "wh3e.class.theFortunate",
  },
  damageDice: {
    oneDmg: "wh3e.damageDice.oneDmg",
    d3: "wh3e.damageDice.d3",
    d4: "wh3e.damageDice.d4",
    d6: "wh3e.damageDice.d6",
    twd6: "wh3e.damageDice.twd6",
    thd6: "wh3e.damageDice.thd6",
    d8: "wh3e.damageDice.d8",
    fd8: "wh3e.damageDice.fd8",
    d10: "wh3e.damageDice.d10",
    twd10: "wh3e.damageDice.twd10",
    d12: "wh3e.damageDice.d12",
    twd12: "wh3e.damageDice.twd12",
  },
  weaponWeightTypes: {
    negligible: "wh3e.weightTypes.negligible",
    small: "wh3e.weightTypes.small",
    regular: "wh3e.weightTypes.regular",
    heavy: "wh3e.weightTypes.heavy",
  },
  gearWeightTypes: {
    regular: "wh3e.weightTypes.regular",
    heavy: "wh3e.weightTypes.heavy",
        small: "wh3e.weightTypes.small",
    negligible: "wh3e.weightTypes.negligible",
    noEncumbrance: "wh3e.weightTypes.noEncumbrance",
  },
  roFShotsPerRound: {
    none: "wh3e.misc.none",
    oneInFour: "wh3e.roFShotsPerRound.oneInFour",
    oneInThree: "wh3e.roFShotsPerRound.oneInThree",
    oneInTwo: "wh3e.roFShotsPerRound.oneInTwo",
    one: "wh3e.roFShotsPerRound.one",
    three: "wh3e.roFShotsPerRound.three",
  },
  abilityTypes: {
    attunement: "wh3e.abilityType.attunement",
    combatOption: "wh3e.abilityType.combatOption",
    miracle: "wh3e.abilityType.miracle",
    quirk: "wh3e.abilityType.quirk",
    species: "wh3e.abilityType.species",
    vocation: "wh3e.abilityType.vocation",
    affiliation: "wh3e.abilityType.affiliation",
  },
  coinTypes: {
    cash: "wh3e.coinType.cash",
  },
  armorClasses: {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    plusOne: "+1",
    special: "wh3e.item.special",
  },
  monsterarmorClasses: {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
  },
};
